### course page query
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "courseName": "java",
  "audiStatus": "202002"
}

### course classic treeNodes
GET {{content_host}}/content/course-category/tree-nodes?id=1

### create a new course
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 999,
  "originalPrice":888,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "",
  "st": "",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "测试测试测测测测测"
}

### query course base info by Id
GET {{content_host}}/content/course/1

### teachPlan
GET {{content_host}}/content/teachplan/25/tree-nodes

### update or create teachPlan
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "id": 3,
  "courseId" : 25,
  "parentid": 43,
  "grade" : 2,
  "pname" : "sql查询"
}

### delete teachPlan by id
DELETE {{content_host}}/content/teachplan/153

### query course teacher by courseId
GET {{content_host}}/content/courseTeacher/list/72

### add new Course teacher info
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": "999",
  "teacherName": "999",
  "position": "666",
  "introduction": "66667"
}

###  update Course teacher info
PUT {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 22,
  "courseId": 999,
  "teacherName": "999666",
  "position": "666555",
  "introduction": "66667888899",
  "photograph": "www.baidu.com"
}

### delete a course teacher by id && courseId
DELETE {{content_host}}/content/courseTeacher/course/21/999

### delete course by id
DELETE {{content_host}}/content/course/124

### publish
POST {{content_host}}/content/coursepublish/124

### search
GET {{search_host}}/search/course/list

### create index
POST {{search_host}}/search/index/course
JSON
### 添加课程索引
POST {{search_host}}/search/index/course
Content-Type: application/json

{
  "charge" : "201000",
  "companyId" : 100000,
  "companyName" : "北京黑马程序员",
  "createDate" : "2022-09-25 09:36:11",
  "description" : "《Java编程思想》是2007年6月1日机械工业出版社出版的图书，作者是埃克尔，译者是陈昊鹏。主要内容本书赢得了全球程序员的广泛赞誉，即使是最晦涩的概念，在Bruce Eckel的文字亲和力和小而直接的编程示例面前也会化解于无形。从Java的基础语法到最高级特性（深入的面向对象概念、多线程、自动项目构建、单元测试和调试等），本书都能逐步指导你轻松掌握。从本书获得的各项大奖以及来自世界各地的读者评论中，不难看出这是一本经典之作",
  "grade" : "204001",
  "id" : 102,
  "mt" : "1-3",
  "mtName" : "编程开发",
  "name" : "Java编程思想",
  "originalPrice" : 200.0,
  "pic" : "/mediafiles/2022/09/20/1d0f0e6ed8a0c4a89bfd304b84599d9c.png",
  "price" : 100.0,
  "remark" : "没有备注",
  "st" : "1-3-2",
  "stName" : "Java语言",
  "status" : "203002",
  "tags" : "没有标签",
  "teachmode" : "200002",
  "validDays" : 222
}

### test auth code
GET {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=授权码&redirect_uri=http://www.51xuecheng.cn/


### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=CTvCrB&redirect_uri=http://www.51xuecheng.cn
